opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - explicit_type_interface
  - fatal_error_message
  - first_where
  - for_where
  - force_unwrapping
  - implicit_getter
  - implicit_return
  - joined_default_parameter
  - legacy_constructor
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension 
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - redundant_set_access_control
  - single_test_class
  - sorted_first_last
  - strict_fileprivate
  - switch_case_alignment
  - switch_case_on_newline
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_closure_parameter
  - vertical_parameter_alignment_on_call
  - yoda_condition
disabled_rules:
  - type_name 
  - file_length
  - function_body_length
  - type_body_length
  - file_name
  - line_length
identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - ui
    - cg
    - x
    - y
modifier_order:
  preferred_modifier_order: ["acl"]
explicit_type_interface:
  excluded:
    - local
